name: "Deploy or upgrade the core smart contracts"
description: "Trigger a deployment to a network."
title: "Leave the title blank as the workflow will override it"
labels:
  - "Deploy"
body:
  - type: "markdown"
    attributes:
      value: "# Network Configurations Status Overview\n\n| Network | Address | RPC_URL | PRIVATE_KEY | ETHERSCAN_API_KEY | ETHERSCAN_BASE_API_URL | SIGNATURE_CHECKER_NAME |\n|---------|---------|---------|-------------|-------------------|------------------------|------------------------|\n ✅ | ✅ | ✅ | ✅ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n ❌ | ❌ | ❌ | ❌ | ✅ |\n"
  - type: "dropdown"
    id: "networkName"
    attributes:
      label: "Network Name"
      description: "Select a network for deployment"
      options:
        - "ETHEREUM_SEPOLIA"
        - "STAGING"
        - "UAT"
        - "PROD_MAINNET"
        - "PROD_ARBITRUM"
        - "PROD_BASE"
        - "PROD_OPTIMISM"
        - "PROD_AVALANCHE"
        - "PROD_ZKSYNC"
        - "PROD_POLYGON"
    validations:
      required: true
  - type: "input"
    id: "tagOrCommit"
    attributes:
      label: "Tag semver or Commit hash"
      description: "Get the tag or commit hash from the Github page of the KeyringCore repo."
    validations:
      required: true
  - type: "textarea"
    id: "comments"
    attributes:
      label: "Comments"
      description: "Add comments related to this deployment"
      placeholder: "This is a new deployment for the Foo network as ..."
    validations:
      required: false
