name: Deployment
description: Trigger a deployment to a network.
title: "[Deployment]: "
labels: ["deployment"]
body:
  - type: markdown
    attributes:
      value: |
        Deploy or upgrade KeyringCore to a network.
  - type: input
    id: networkName
    attributes:
      label: Network Name
      description: For upgrade, pick the name in the /networks folder. For new deployment, use a new name. Network name must be all uppercase letters, numbers, and hyphens.
    validations:
      required: true
  - type: input
    id: tagOrCommit
    attributes:
      label: Tag semver or Commit hash
      description: Get the tag or commit hash from the Github page of the KeyringCore repo.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Comments
      description: Add comments related to this deployment
      placeholder: This is a new deployment for the Foo network as ...
    validations:
      required: false
