name: "Deploy or upgrade the core smart contracts"
description: "Trigger a deployment to a network."
title: "Leave the title blank as the workflow will override it"
labels:
  - "Deploy"
body:
  - type: "markdown"
    attributes:
      value: "## Network Configurations Status Overview\n\n| Network | PROXY_ADDRESS | RPC_URL | ETHERSCAN | SIGNATURE_CHECKER_NAME |\n|---------|---------|---------|-------------|-------------------|------------------------|------------------------|\n ARBITRUM_MAINNET.json | ✅0x | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n AVALANCHE_MAINNET.json | ✅0x88e097C960aD0239B4eEC6E8C5B4f74f898eFdA3 | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n BASE_MAINNET.json | ✅0x88e097C960aD0239B4eEC6E8C5B4f74f898eFdA3 | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n ETHEREUM_MAINNET.json | ✅0xD18d17791f2071Bf3C855bA770420a9EdEa0728d | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n ETHEREUM_TESTNET.json | ✅0x | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n OPTIMISM_MAINNET.json | ✅0x88e097C960aD0239B4eEC6E8C5B4f74f898eFdA3 | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n POLYGON_MAINNET.json | ✅0x | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n ZKSYNC_MAINNET.json | ✅0x617534538624ae12AC8F5A12cbC22491FED7D63D | ❌ | - _API_KEY: ❌ \n - _BASE_API_URL: ✅ \n ✅ |\n"
  - type: "markdown"
    attributes:
      value: "## Deployment options"
  - type: "dropdown"
    id: "networkName"
    attributes:
      label: "Network Name"
      description: "Select a network for deployment"
      options:
        - "ARBITRUM_MAINNET.json"
        - "AVALANCHE_MAINNET.json"
        - "BASE_MAINNET.json"
        - "ETHEREUM_MAINNET.json"
        - "ETHEREUM_TESTNET.json"
        - "OPTIMISM_MAINNET.json"
        - "POLYGON_MAINNET.json"
        - "ZKSYNC_MAINNET.json"
    validations:
      required: true
  - type: "input"
    id: "tagOrCommit"
    attributes:
      label: "Tag semver or Commit hash"
      description: "Get the tag or commit hash from the Github page of the KeyringCore repo."
    validations:
      required: true
  - type: "input"
    id: "tagOrCommit"
    attributes:
      label: "Broadcast the deployment transactions"
      description: "If not checked, will only perform a simulation of the deployment. This is useful to check if the deployment will be successful before broadcasting the transactions."
    validations:
      required: false
  - type: "textarea"
    id: "comments"
    attributes:
      label: "Comments"
      description: "Add comments related to this deployment"
      placeholder: "This is a new deployment for the Foo network as ..."
    validations:
      required: false
