name: Deployment

# Add permissions configuration
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  check-and-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'deployment')
    steps:
      - name: Add initial comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Workflow began'
            })
