name: Refresh Network Configurations

permissions:
  issues: write
  contents: write

on:
  push:
  pull_request:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Check Network Configurations and Update Template
        uses: actions/github-script@v6
        env:
          CREDENTIALS: ${{ secrets.credentials }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const yaml = require('./node_modules/js-yaml');
            const credentials = JSON.parse(process.env.CREDENTIALS);

            // list all the networks in the /networks folder  
            const networks = fs.readdirSync('./networks');

            let networkTable = '## Network Configurations Status Overview\n\n';
            networkTable += '| Network | PROXY_ADDRESS | RPC_URL | ETHERSCAN_API_KEY | ETHERSCAN_BASE_API_URL | SIGNATURE_CHECKER_NAME |\n';
            networkTable += '|---------|--------------|---------|------------------|---------------------|----------------------|\n';

            for (const network of networks) {
              const config = JSON.parse(fs.readFileSync(`./networks/${network}`, 'utf8'));
              const networkName = network.replace('.json', '');
              networkTable += `| ${networkName} |`;
              networkTable += ` ${config.PROXY_ADDRESS ? '✅' + config.PROXY_ADDRESS : '❌'} |`;
              networkTable += ` ${config.RPC_URL ? '✅' : '❌'} |`;
              networkTable += ` ${config.ETHERSCAN_API_KEY ? '✅' : '❌'} |`;
              networkTable += ` ${config.ETHERSCAN_BASE_API_URL ? '✅' : '❌'} |`;
              networkTable += ` ${config.SIGNATURE_CHECKER_NAME ? '✅' : '❌'} |\n`;
            }

            const templatePath = '.github/ISSUE_TEMPLATE/deployment.yml';
            const template = yaml.load(fs.readFileSync(templatePath, 'utf8'));

            // Update the template with unique IDs and network names without .json extension
            template.body[0].id = 'network-status';
            template.body[0].attributes.value = networkTable;

            template.body[1].id = 'network-name';
            template.body[2].id = 'network-select';
            template.body[2].attributes.options = networks.map(network => network.replace('.json', ''));

            fs.writeFileSync(templatePath, yaml.dump(template, {
              lineWidth: -1,
              quotingType: '"',
              forceQuotes: true
            }));

            await exec.exec('git', ['config', '--global', 'user.email', 'github-actions[bot]@users.noreply.github.com']);
            await exec.exec('git', ['config', '--global', 'user.name', 'github-actions[bot]']);

            console.log('\nGit status:');
            await exec.exec('git', ['status']);

            await exec.exec('git', ['add', '.github/ISSUE_TEMPLATE/deployment.yml']);
            await exec.exec('git', ['commit', '-m', 'chore: update network options and status table in deployment template']);
            await exec.exec('git', ['push']);
